### ISSUE TITLE
Make nav landing WCAG compliant

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/nav-landing-page#16]
Following 47 requirements are satisfied:

- [x] WCAG 2. 0 - 1.1.1
- [x] WCAG 2. 0 - 1.2.1
- [x] WCAG 2. 0 - 1.2.2
- [x] WCAG 2. 0 - 1.3.1
- [x] WCAG 2. 0 - 1.3.2
- [x] WCAG 2. 0 - 1.3.3
- [x] WCAG 2. 0 - 1.4.1
- [x] WCAG 2. 0 - 1.4.2
- [x] WCAG 2. 0 - 1.4.3
- [x] WCAG 2. 0 - 1.4.4
- [x] WCAG 2. 0 - 1.4.5
- [x] WCAG 2. 0 - 2.1.1
- [x] WCAG 2. 0 - 2.1.2
- [x] WCAG 2. 0 - 2.2.1
- [x] WCAG 2. 0 - 2.2.2
- [x] WCAG 2. 0 - 2.3.1
- [x] WCAG 2. 0 - 2.4.1
- [x] WCAG 2. 0 - 2.4.2
- [x] WCAG 2. 0 - 2.4.3
- [x] WCAG 2. 0 - 2.4.4
- [x] WCAG 2. 0 - 2.4.5
- [x] WCAG 2. 0 - 2.4.6
- [x] WCAG 2. 0 - 2.4.7
- [x] WCAG 2. 0 - 3.1.1
- [x] WCAG 2. 0 - 3.1.2
- [x] WCAG 2. 0 - 3.2.1
- [x] WCAG 2. 0 - 3.2.2
- [x] WCAG 2. 0 - 3.2.3
- [x] WCAG 2. 0 - 3.2.4
- [x] WCAG 2. 0 - 3.3.1
- [x] WCAG 2. 0 - 3.3.2
- [x] WCAG 2. 0 - 3.3.3
- [x] WCAG 2. 0 - 3.3.4
- [x] WCAG 2. 0 - 4.1.1
- [x] WCAG 2. 0 - 4.1.2
-----
- [x] WCAG 2.1 - 1.3.4
- [x] WCAG 2.1 - 1.3.5
- [x] WCAG 2.1 - 1.4.10
- [x] WCAG 2.1 - 1.4.11
- [x] WCAG 2.1 - 1.4.12
- [x] WCAG 2.1 - 1.4.13
- [x] WCAG 2.1 - 2.1.4
- [x] WCAG 2.1 - 2.5.1
- [x] WCAG 2.1 - 2.5.2
- [x] WCAG 2.1 - 2.5.3
- [x] WCAG 2.1 - 2.5.4
- [x] WCAG 2.1 - 4.1.3
-------

TODOs:

- [x] #21
- [x] #22
- [x] #23
- [x] #28

**Comment by lunkwill42** [comment]
This was fixed and put in production several weeks ago! :)
